### PR TITLE
Suggestion for improved 6.x API

### PR DESCRIPTION
**Pull request by stefanb2**
* instead of hard-coding the API by overriding the Koa application API add a private listen method
* instead of maintaining own middleware stack, re-use middleware stack from application
* automatically close websocket on middleware errors
* use ES6
* update examples to new API

Tests still need to be updated...

### CODE REVIEW

**Comment by kudos** [comment]
@stefanb2 if you're still interested in contributing, can you try to reformat the code to match the existing style? I'll add an eslint config so it's more clear in future.

**Comment by stefanb2** [comment]
* rebased to master
* API change from 5.x -> 6.x
* updated tests for new API

@kudos I would prefer you to reformat the code to your expectations. I have used my own `.eslintrc.json`and get a passing result with 4 warnings (console usage in examples).

**Comment by kudos** [comment]
@stefanb2 I've added airbnb's eslint config, if you rebase and fix conflicts running `eslint --fix .` should take care of virtually all of the formatting differences automatically. Unfortunately I had to reformat the code to match airbnb's standard and that will cause conflicts when you rebase.

**Comment by stefanb2** [comment]
I tried to rebase, but IMHO the ESlint configuration doesn't make any sense. I understand the errors about some indentations, but others just make the code unreadable. Then there are the errors which can only be fixed by breaking the code or introducing syntax errors?

Sorry, but I have better things to do than wasting it on this. Take it or leave it, I leave that decision up to you. If you don't take this PR then please at least take the one that adds the examples, because those are valuable to others.

**Comment by stefanb2** [comment]
For people still interested in the improved API: I have pushed my rebase to https://github.com/stefanb2/koa-websocket/tree/topic-suggested-5.x-api

Please note that linter errors that will require breaking the code are not fixed.

**Comment by kudos** [comment]
Thanks, I make take this on with the rebase out of the way.

**Pull request closed without merging**
